### ISSUE TITLE
IPv6 for LanScan

### ISSUE THREAD

**Issue by AWHubGit** [iwaxx/blog#12]
I bought LanScan 6.15.13 for macOS 12.1.

I have IPv6 on my LAN and want to migrate to IPv6 for all devices.

Does LanScan also work with/for IPv6? How? When?

**Comment by debookee** [comment]
IPv6 scanning is a missing feature of our apps, we plan to introduce in coming features though !

Meanwhile, maybe you're aware of the powerful command line "ndp -an" to be launch in a Terminal.

**Comment by AWHubGit** [comment]
Hi

very happy to see LanScan expanding to IPv6! Thanks.

"ndp -ant" on my macOS 13.2.1 shows also entries for ULAs like "fd00::xxxxx".

Don't forget these. Very important:
[https://networkengineering.stackexchange.com/questions/50146/is-it-true-that-the-fd00-8-address-range-ula-in-ipv6-is-for-machines-that-yo](https://networkengineering.stackexchange.com/questions/50146/is-it-true-that-the-fd00-8-address-range-ula-in-ipv6-is-for-machines-that-yo)

**Comment by debookee** [comment]
Thanks for your comment. Indeed, ULA and also Site-Local are already ready to be accepted by LanScan.

Two things though :
With your comment, I realized that the "IPv6 Link-Local" column header was not correct and change it to "IPv6 Local" (For Link-Local, Site-Local and ULA, and ...(?))

For your knowledge in LanScan behavior, those are only 2 columns, Global & Local, but 1 interface can have dozens of IPv6 (even Global adresses can be temporary, secured, etc ...)
→ For the moment, the pane Details on right will contain all IPv6 adresses found in the field "IPv6 Addresses".

To sum-up : only 2 columns (most common case for average user), but all found IPv6 for one MAC address in "Details" pane.
