### ISSUE TITLE
hostname grey (greyed-out) in Debookee

### ISSUE THREAD

**Issue by AWHubGit** [iwaxx/blog#14]
What does it mean/signify if/when a hostname in the result list ist grey only (greyed-ount) and not black as other hostnames?

**Comment by debookee** [comment]
Hi, we use grey color for custom names (and comments) : means you double-clicked or edited the default hostnames.
If you edit & delete the grey hostname, then you'll see the default hostnames in black appearing again.

For more info or troubleshooting, contact us by email with screenshots : support@iwaxx.com
